"""
main.py — Runs SFF on the production extract, or on the synthetic raw.

    python main.py              # the production extract (SQL Server)
    python main.py sintetico    # the synthetic raw of the tests

The Config is declared here and only here: its columns, its calendar and where the raw
comes from. Each step adds one line to run().
"""

# ─── imports ─────────────────────────────────────────────────────────────────────
import os
import sys

import pandas as pd
from sqlalchemy import create_engine

from pipeline import Orchestrator
from config import Config


# ─── named constants ─────────────────────────────────────────────────────────────
SQL_SERVER = "..."                          # [por completar]
SQL_DATABASE = "..."                        # [por completar]
SQL_DRIVER = "ODBC Driver 17 for SQL Server"
RAW_EXTRACT_QUERY = "SELECT * FROM ..."     # [por completar] the query of the raw extract
SYNTHETIC_KEYWORD = "sintetico"
SYNTHETIC_OUTPUT_FOLDER = "salida"
SYNTHETIC_DATABASE = os.path.join(SYNTHETIC_OUTPUT_FOLDER, "sff_sintetico.db")


# ═══════════════════════════════════════════════════════════════════════════════════
# THE TWO CONFIGS
# ═══════════════════════════════════════════════════════════════════════════════════

def production_engine():
    """The production SQL Server: the raw is read from it and the tables are written to it.
    fast_executemany: pyodbc sends every chunk of to_sql in one round trip (without it, one
    INSERT per row: a table of a million rows takes minutes instead of seconds)."""
    connection_url = (f"mssql+pyodbc://@{SQL_SERVER}/{SQL_DATABASE}"
                      f"?driver={SQL_DRIVER.replace(' ', '+')}&trusted_connection=yes")
    return create_engine(connection_url, fast_executemany=True)


class ProductionConfig(Config):
    def read_raw(self) -> pd.DataFrame:
        return pd.read_sql(self.raw_extract_sql, self.sql_engine)


class SyntheticConfig(Config):
    def read_raw(self) -> pd.DataFrame:
        from synthetic_v3 import build_raw
        return build_raw(7, with_discount_pct=True)


def production_configuration() -> Config:
    """The production extract, as seen in the runs of 29-sep. Names marked [por confirmar]
    must be checked against it: step 00 names every column that is missing or has no role."""
    return ProductionConfig(
        # where the raw is read from and the tables are written to
        sql_engine=production_engine(),
        sql_schema="dbo",
        raw_extract_sql=RAW_EXTRACT_QUERY,
        # the calendar
        current_month="01/09/2026",
        test_months=3,
        # the dimensions
        business_mandatory_dims=["tr_regional_level_1", "tr_regional_level_2", "tr_regional_level_3",
                                 "tr_product_level_1", "tr_product_level_2", "tr_purchase_type", "tr_renewal_type",
                                 "tr_term_level_1", "tr_term_level_2", "tr_band_level_1", "tr_band_level_2",
                                 "tr_master_partner_code"],
        # term and band: level_2 = the raw value of the extract, level_1 = generated by the library (step 02b;
        # the extract's own level_1 is overwritten). The groups are kept in salida/sff_levels.json
        leveled_dims={"tr_term": {"source": "tr_term_level_2", "type": "ordinal"},
                      "tr_band": {"source": "tr_band_level_2", "type": "ordinal"}},
        structural_timevarying_dims={"dormant": "negative", "softcancel": "negative",
                                     "not_installed": "negative"},            # [por confirmar] the signs
        extra_renovacion=["net_new", "prev_OperationGroup"],
        extra_revalorizacion=["price_cap", "msrp_increased"],
        # the discount: ONE column, both sides (the bucket is derived with the default edges,
        # the same as the extract's old discount_interval)
        discount_value_column="discount",
        # the other columns of the extract
        extra_measure_cols=["total_reacquired_units", "total_reacquired_usd", "TR_AUV", "REN_AUV", "ReAC_AUV"],
        ignore_cols=["dataset_role", "is_current_month", "dummy_field", "row_id", "_filter"],   # [por confirmar]
        # the simulation window (current month → December): what happens in it falls due in 2027
        term_column="tr_term_level_2",
        one_year_term_value="1 year",
        acquisition_column="net_new",
        acquisition_values=["Acquisition_Not-New", "Acquisition_Pure-New"],
        acquisition_discount=0.4,
        # the time_series universe (retail to subscription): its region and its projection
        ts_region_columns=["tr_regional_level_1", "tr_regional_level_2", "tr_regional_level_3"],   # projected by country
    )


def synthetic_configuration() -> Config:
    """The synthetic raw of the tests: 2023-01..2026-12, current month 2026-09. Its tables
    go to a SQLite file in salida/."""
    os.makedirs(SYNTHETIC_OUTPUT_FOLDER, exist_ok=True)
    return SyntheticConfig(
        sql_engine=create_engine(f"sqlite:///{SYNTHETIC_DATABASE}"),
        current_month="2026-09",
        test_months=3,
        business_mandatory_dims=["region", "product"],
        structural_timevarying_dims={"dormant": "negative", "softcancel": "negative",
                                     "no_instalado": "negative", "autorenew": "positive"},
        extra_renovacion=["channel"],
        extra_revalorizacion=["newcust"],
        # the synthetic carries the exact discount as discount_pct and its own bucket as
        # discount: the framework derives the bucket, so the synthetic's is ignored
        discount_value_column="discount_pct",
        ignore_cols=["dataset_role", "is_current_month", "discount"],
        # the simulation window: acquisitions are newcust = 1
        acquisition_column="newcust",
        acquisition_values=[1],
    )


# ═══════════════════════════════════════════════════════════════════════════════════
# THE RUN
# ═══════════════════════════════════════════════════════════════════════════════════

def run(configuration: Config) -> dict:
    """Every step, in the order of their dependencies (pipeline.py: contracts, step interface, orchestrator)."""
    return Orchestrator(configuration).run()


if __name__ == "__main__":
    if SYNTHETIC_KEYWORD in sys.argv[1:]:
        run(synthetic_configuration())
    else:
        run(production_configuration())
