"""
step_21_new_rows.py — The rows the framework adds or wipes, month by month, in one format.

The forecast does not use the extract as it comes. Four kinds of rows are added or wiped, each for a
reason, and this step puts them side by side so they can be explained:

  hueco                        step 08 · a forecast unit with nothing due, added inside the history of
                               an estimable series so its monthly series has no holes (the techniques
                               read consecutive months: a trend, a season, a moving average). Every
                               measure is 0: it adds a month, not money.
  resultado_adelantado_borrado step 02 · a renewal already booked from the current month on: the month
                               has not finished (or has not started); the forecast predicts it instead.
  pipeline_parcial_borrada     step 02 · the PARTIAL pipeline of the 1-year licences due 12 months after
                               the current month or later: it is generated by the sales and renewals
                               from the current month on, which have only started (the current month is
                               half way, the next ones have not begun). Left as it is, the forecast of
                               those months would run on a pipeline half built; step 17 rebuilds it whole.
  proyectada                   step 17 · the expected renewal of a 1-year licence due in the simulation
                               window, due 12 months later: what replaces the wiped pipeline.
  simulada                     step 17 · an acquisition simulated in the simulation window, due 12 months
                               later: also replaces wiped pipeline.

One row per month × origin: rows, series, units and USD (due, or wiped), and USD expected to renew for
the rows the forecast predicts. It is a REPORT, not a table of the run: everything in it is a query over
sff_nucleo, and the step prints that query (report_queries.py) instead of writing a second copy.

Actions (logged as they are done):
  1. the gaps of step 08
  2. what step 02 wiped (from the s0_ columns of the fine table)
  3. what step 17 created
  4. the table: month × origin; the totals per origin, side by side
  5. check that the raw = what stays + what was wiped                    check 1
  6. count the checks; stop if any failed
  7. show the totals per origin and the months with activity, as tables, and the SQL that reproduces them

Checks (logged as they are made, numbered, at the level of their status):
   1. what the raw had due = what stays due + the partial pipeline wiped (units and USD)
"""

# ─── imports ─────────────────────────────────────────────────────────────────────
import numpy as np
import pandas as pd

from config import Config
from report_queries import new_rows_query
from vocabulario import (CALENDAR_ROLE_COLUMN, PIPELINE_ORIGIN_COLUMN, PIPELINE_PROJECTED, PIPELINE_SIMULATED,
                         S0_PIPELINE_UNITS_COLUMN, S0_PIPELINE_USD_COLUMN, S0_RENEWED_UNITS_COLUMN, S0_RENEWED_USD_COLUMN,
                         SERIES_ID_COLUMN, SYNTHETIC_COLUMN)


STEP_LABEL = "21"
STEP_NAME = "THE ROWS THE FRAMEWORK ADDS OR WIPES"
STEP_PURPOSE = ("put side by side, month by month and in one format, every row the framework adds or wipes: the gaps "
                "that make the monthly series continuous, what the calendar wipes because it is not known yet, and what "
                "the forecast creates to replace it")
STEP_ACTIONS = ["the gaps of step 08",
                "what step 02 wiped (from the s0_ columns of the fine table)",
                "what step 17 created",
                "the table: month × origin; the totals per origin, side by side",
                "check that the raw = what stays + what was wiped (check 1)",
                "count the checks; stop if any failed",
                "show the totals per origin and the months with activity, as tables, and the SQL that reproduces them"]
STEP_OUTPUT = "one row per month × origin (rows, series, units, USD, USD expected): a report, with its SQL over sff_nucleo"

ORIGIN_GAP = "hueco"
ORIGIN_WIPED_RESULT = "resultado_adelantado_borrado"
ORIGIN_WIPED_PIPELINE = "pipeline_parcial_borrada"
ORIGINS_IN_ORDER = [ORIGIN_GAP, ORIGIN_WIPED_RESULT, ORIGIN_WIPED_PIPELINE, PIPELINE_PROJECTED, PIPELINE_SIMULATED]
WHAT_IT_IS = {ORIGIN_GAP: "added (step 08): a month with nothing due inside the history of a series, so it has no holes",
              ORIGIN_WIPED_RESULT: "wiped (step 02): a renewal booked from the current month on; the forecast predicts it",
              ORIGIN_WIPED_PIPELINE: "wiped (step 02): partial pipeline of 1-year licences, half built by sales and renewals that have only started",
              PIPELINE_PROJECTED: "created (step 17): expected renewal of a 1-year licence due in the window, 12 months later",
              PIPELINE_SIMULATED: "created (step 17): acquisition simulated in the window, due 12 months later"}
UNITS_TOLERANCE = 1e-6


def count_the_new_rows(fine_table: pd.DataFrame, rated_units: pd.DataFrame, forecast_rows: pd.DataFrame,
                       configuration: Config) -> pd.DataFrame:
    """The rows added or wiped, one row per month × origin.

    INPUT:   the fine table (step 03, with the s0_ columns of step 02) · the forecast units with the gaps (step 08)
             · the future rows of the forecast (step 17).
    OUTPUT:  month × origin: rows, series, units, USD, USD expected (a report: its SQL over sff_nucleo is printed).
    RULES:   counts what the steps did; computes nothing new.
    EDGE CASES: an origin with no rows does not appear; a run without a simulation window has no proyectada / simulada.
    """
    configuration.log_step_start(STEP_LABEL, STEP_NAME, STEP_PURPOSE, STEP_ACTIONS, STEP_OUTPUT)
    check_log = []
    period, due_units, due_usd = configuration.period_col, configuration.pipeline_units_col, configuration.pipeline_usd_col
    parts = []

    # [1] the gaps
    gaps = rated_units[rated_units[SYNTHETIC_COLUMN] == 1]
    parts.append(summarise(gaps, ORIGIN_GAP, period, units=0.0, usd=0.0))
    configuration.log_action(STEP_LABEL, 1, f"{len(gaps):,} gap rows in {gaps[SERIES_ID_COLUMN].nunique():,} series "
                                            f"(every measure 0: a month, not money)")

    # [2] what the calendar wiped
    wiped_result = fine_table[fine_table[S0_RENEWED_UNITS_COLUMN].fillna(0) > fine_table[configuration.renewed_units_col].fillna(0)]
    parts.append(summarise(wiped_result, ORIGIN_WIPED_RESULT, period,
                           units=wiped_result[S0_RENEWED_UNITS_COLUMN].fillna(0) - wiped_result[configuration.renewed_units_col].fillna(0),
                           usd=wiped_result[S0_RENEWED_USD_COLUMN].fillna(0) - wiped_result[configuration.renewed_usd_col].fillna(0)))
    wiped_pipeline = fine_table[fine_table[S0_PIPELINE_UNITS_COLUMN] > fine_table[due_units] + UNITS_TOLERANCE]
    parts.append(summarise(wiped_pipeline, ORIGIN_WIPED_PIPELINE, period,
                           units=wiped_pipeline[S0_PIPELINE_UNITS_COLUMN] - wiped_pipeline[due_units],
                           usd=wiped_pipeline[S0_PIPELINE_USD_COLUMN] - wiped_pipeline[due_usd]))
    configuration.log_action(STEP_LABEL, 2, f"wiped by the calendar: {len(wiped_result):,} rows of early results · "
                                            f"{len(wiped_pipeline):,} rows of pipeline not known yet")

    # [3] what the forecast created
    for origin in (PIPELINE_PROJECTED, PIPELINE_SIMULATED):
        created = forecast_rows[forecast_rows[PIPELINE_ORIGIN_COLUMN] == origin] if PIPELINE_ORIGIN_COLUMN in forecast_rows else forecast_rows.iloc[0:0]
        parts.append(summarise(created, origin, period, units=created[due_units], usd=created[due_usd],
                               expected=created["esperado_usd"] if "esperado_usd" in created else None))
    configuration.log_action(STEP_LABEL, 3, "created by the forecast: " + " · ".join(
        f"{origin} {int((forecast_rows[PIPELINE_ORIGIN_COLUMN] == origin).sum()) if PIPELINE_ORIGIN_COLUMN in forecast_rows else 0:,} rows"
        for origin in (PIPELINE_PROJECTED, PIPELINE_SIMULATED)))

    # [4] the table
    table = pd.concat([part for part in parts if len(part)], ignore_index=True)
    table["origen"] = pd.Categorical(table["origen"], ORIGINS_IN_ORDER, ordered=True)
    table = table.sort_values(["mes", "origen"]).reset_index(drop=True)
    table["origen"] = table["origen"].astype(str)
    roles = configuration.role_of_months(table["mes"])
    table.insert(1, CALENDAR_ROLE_COLUMN, roles)
    totals = totals_per_origin(table)
    configuration.log_action(STEP_LABEL, 4, f"{len(table):,} month × origin rows")

    # [5] the reconciliation with the raw
    configuration.log_action(STEP_LABEL, 5, "checking the reconciliation with the raw")
    raw_units, raw_usd = float(fine_table[S0_PIPELINE_UNITS_COLUMN].sum()), float(fine_table[S0_PIPELINE_USD_COLUMN].sum())
    kept_units, kept_usd = float(fine_table[due_units].sum()), float(fine_table[due_usd].sum())
    wiped = table[table["origen"] == ORIGIN_WIPED_PIPELINE]
    reconciles = (abs(raw_units - kept_units - wiped["unidades"].sum()) <= UNITS_TOLERANCE * max(raw_units, 1)
                  and abs(raw_usd - kept_usd - wiped["usd"].sum()) <= UNITS_TOLERANCE * max(raw_usd, 1))
    configuration.log_check(STEP_LABEL, check_log, "what the raw had due = what stays due + the partial pipeline wiped (units and USD)",
                            reconciles, failure_detail="the wiped pipeline does not explain the difference with the raw",
                            context=f"raw {raw_units:,.0f} units · ${raw_usd:,.0f} = kept {kept_units:,.0f} · ${kept_usd:,.0f} "
                                    f"+ wiped {wiped['unidades'].sum():,.0f} · ${wiped['usd'].sum():,.0f}")

    # [6] the count of the checks
    configuration.log_action(STEP_LABEL, 6, "counting the checks")
    configuration.log_check_summary(STEP_LABEL, STEP_NAME, check_log)

    # [7] the tables and their SQL
    configuration.log_action(STEP_LABEL, 7, "per origin (what each one is, and how much):")
    configuration.show_table(totals)
    configuration.logger.doc(f"[{STEP_LABEL}] the months with wiped or created pipeline (the gaps are spread over the history):")
    configuration.show_table(table[table["origen"] != ORIGIN_GAP].reset_index(drop=True))
    configuration.show_query(STEP_LABEL, "the rows the framework adds or wipes, month × origin", new_rows_query(configuration))
    return table


def summarise(rows: pd.DataFrame, origin: str, period_column: str, units, usd, expected=None) -> pd.DataFrame:
    """One row per month: rows, series, units, USD and USD expected of one origin."""
    if not len(rows):
        return pd.DataFrame()
    frame = pd.DataFrame({"mes": rows[period_column].to_numpy(), SERIES_ID_COLUMN: rows[SERIES_ID_COLUMN].to_numpy(),
                          "unidades": np.broadcast_to(np.asarray(units, dtype=float), len(rows)),
                          "usd": np.broadcast_to(np.asarray(usd, dtype=float), len(rows)),
                          "esperado_usd": (np.asarray(expected, dtype=float) if expected is not None else np.full(len(rows), np.nan))})
    grouped = frame.groupby("mes")
    summary = pd.DataFrame({"filas": grouped.size(), "series": grouped[SERIES_ID_COLUMN].nunique(),
                            "unidades": grouped["unidades"].sum(), "usd": grouped["usd"].sum(),
                            "esperado_usd": grouped["esperado_usd"].sum(min_count=1)}).reset_index()
    summary.insert(1, "origen", origin)
    return summary


def totals_per_origin(table: pd.DataFrame) -> pd.DataFrame:
    """One row per origin: what it is, its months, rows, units, USD and USD expected."""
    rows = []
    for origin in ORIGINS_IN_ORDER:
        block = table[table["origen"] == origin]
        if not len(block):
            continue
        rows.append({"origen": origin, "que_es": WHAT_IT_IS[origin], "meses": f"{block['mes'].min()}..{block['mes'].max()}",
                     "filas": int(block["filas"].sum()), "unidades": float(block["unidades"].sum()), "usd": float(block["usd"].sum()),
                     "esperado_usd": float(block["esperado_usd"].sum()) if block["esperado_usd"].notna().any() else np.nan})
    return pd.DataFrame(rows)
